#!/bin/bash

ALGO=$1

jobfile=$(mktemp)
cat << EOF > $jobfile
#!/bin/bash

#SBATCH --job-name=$ALGO
#SBATCH --output=$ALGO.txt
#SBATCH --error=$ALGO.err
#SBATCH --account=pi_olano
#SBATCH --qos=medium
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markj1@umbc.edu
#SBATCH --partition=high_mem
#SBATCH --nodes=7
#SBATCH --ntasks-per-node=16
##SBATCH --mem-per-cpu=4000

srun ./main --output=/umbc/xfs1/olano/users/markj1/ --big $ALGO

EOF

sbatch $jobfile
