#!/bin/bash

ALGO=$1

jobfile=$(mktemp)
cat << EOF > $jobfile
#!/bin/bash

#SBATCH --job-name=$ALGO
#SBATCH --output=$ALGO.txt
#SBATCH --error=$ALGO.err
#SBATCH --qos=medium
#SBATCH --mail-type=ALL
#SBATCH --mail-user=markj1@umbc.edu
#SBATCH --partition=batch
#SBATCH --array=1-106
#SBATCH --mem-per-cpu=1000

export LD_LIBRARY_PATH=/usr/cluster/contrib/gcc/gcc-5.5.0/{lib,lib64}:/usr/cluster/contrib/testu01/lib:${LD_LIBRARY_PATH}
export LIBRARY_PATH=/usr/cluster/contrib/gcc/gcc-5.5.0/{lib,lib64}:/usr/cluster/contrib/testu01/lib:${LIBRARY_PATH}
export C_INCLUDE_PATH=/usr/cluster/contrib/gcc/gcc-5.5.0/include::/usr/cluster/contrib/testu01/include:${C_INCLUDE_PATH}

srun ./main --big --test=\$SLURM_ARRAY_TASK_ID $ALGO
EOF

sbatch $jobfile
